### PR TITLE
fix helper typo

### PR DESCRIPTION
**Pull request by svoboda-jan**

### CODE REVIEW

**Comment by rzane** [comment]
I'm fairly certain that this wasn't a typo. @svoboda-jan did you test this?

**Comment by svoboda-jan** [comment]
@rzane I found it when I was adding support for FirebirdSQL to [Redmine](https://github.com/svoboda-jan/redmine/tree/firebirdsql). Without this change I get:
`undefined method 'expr' for 25:Fixnum` in pagination.

Also found this issue, seems to be the same problem: https://github.com/rails/arel/pull/377/files

So it looks like it got copy-pasted from another adapter.

**Comment by rzane** [comment]
Alright, sounds like this is okay then. What version of ActiveRecord are you using?

When I added that code, I tested against 4.2.0, `o.limit.expr` was returning an object, rather than a string. I'm thinking this may have been a bug in Arel that has since been fixed.

**Comment by svoboda-jan** [comment]
I'm using `4.2.4`. Tested it now using `4.2.0` with same results (`undefined method 'expr' for 25:Fixnum `) without the patch.

**Comment by rzane** [comment]
Hmm... well okay! Thanks for your contribution.

**Pull request merged**
